agenda/Controllers/AppointmentController.cs
using Microsoft.AspNetCore.Mvc;
using agenda.Models;
using agenda.Data;

namespace agenda.Controllers
{
    public class AppointmentController : Controller
    {
        readonly agendaContext _db;

        public AppointmentController(agendaContext db)
        {
            _db = db;
        }
        public IActionResult Listappointment()
        {
            IEnumerable<Appointment> appointmentsList = _db.Appointments;
            return View(appointmentsList);
        }

        public ActionResult AddAppointment()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddAppointment(Appointment ap)
        {
            _db.Appointments.Add(ap);
            _db.SaveChanges();
            return RedirectToAction("listAppointment");

        }

        public void GetBrokers()
        {
            ViewBag.Brokers = _db.Brokers.ToList();
        }

    }
}

agenda/Controllers/BrokerController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using agenda.Models;
using agenda.Data;

namespace agenda.Controllers
{
    public class BrokerController : Controller
    {
        
        readonly agendaContext _db;

        public BrokerController(agendaContext db)
        {
            _db = db;

        }

        public IActionResult ListBrokers()
        {
            IEnumerable<Broker> brokerList = _db.Brokers;
            return View(brokerList);
        }
        public IActionResult ProfilBrokers(int id)
        {
            Broker? broker = _db.Brokers.Find(id);
            return View(broker);
        }

        // GET: BrokerController
        public ActionResult Index()
        {
            return View();
        }

        // GET: BrokerController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: BrokerController/Create
        public ActionResult CreateBroker()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CreateBroker(Broker broker)
        {
                _db.Brokers.Add(broker);
                _db.SaveChanges();
                return RedirectToAction("listBrokers");
    
        }

        // POST: BrokerController/Create
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            //try
            //{
            //    return RedirectToAction(nameof(Index));
            //}
            //catch
            //{
                return View(collection);
            
        }

        // GET: BrokerController/Edit/5
        public ActionResult Edit(int id)
        {
            Broker? bro = _db.Brokers.Find(id);
            return View(bro);
        }

        // POST: BrokerController/Edit/5
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Edit(Broker bro)
        {
            //try
            //{
            //    return RedirectToAction(nameof(ListBrokers));
            //}
            //catch
            //{

            //    return View(bro);
            //}

           
            _db.Brokers.Update(bro);
            _db.SaveChanges();
            return RedirectToAction("ListBrokers");
        }

        // GET: BrokerController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: BrokerController/Delete/5
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }


        public ActionResult Afficher(int id)
        {
            Broker? bro = _db.Brokers.Find(id);
            return View(bro);
        }



    }


}

agenda/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using agenda.Models;
using agenda.Data;

namespace agenda.Controllers
{
    public class CustomerController : Controller
    {
        readonly agendaContext _db;

        public CustomerController(agendaContext db)
        {
            _db = db ?? throw new ArgumentNullException(nameof(db));

        }

        public IActionResult ListCustomers()
        {
            IEnumerable<Customer> customerList = _db.Customers;
            return View(customerList);
        }

        // GET: CustomerController
        public ActionResult Index()
        {
            return View();
        }

        // GET: CustomerController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        public ActionResult AddCustomer()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddCustomer(Customer customer)
        {
            _db.Customers.Add(customer);
            _db.SaveChanges();
            return RedirectToAction("listCustomers");

        }


        // GET: CustomerController/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        //// POST: CustomerController/Create
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create(IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        // GET: CustomerController/Edit/5
        //public ActionResult Edit(int id)
        //{
        //    return View();
        //}

        //// POST: CustomerController/Edit/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        // GET: CustomerController/Delete/5
        public ActionResult Delete(int id)
        {
            Customer? cust = _db.Customers.Find(id);  
            return View(cust);
        }

        public ActionResult ProfilCustomer(int id)
        {
            Customer? cust = _db.Customers.Find(id);
            return View(cust);
        }

        public ActionResult Edit(int id)
        {
            Customer? cust = _db.Customers.Find(id);
            return View(cust);
        }

        // POST: BrokerController/Edit/5
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Edit(Customer cust)
        {
            _db.Customers.Update(cust);
            _db.SaveChanges();
            return RedirectToAction("ListCustomers");
        }


        // POST: CustomerController/Delete/5
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Delete(Customer custom)
        {
            _db.Customers.Remove(custom);
            _db.SaveChanges();
            return RedirectToAction("ListCustomers");
        }
    }
}

agenda/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Agenda database</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/agenda.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">agenda databse</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">INDEX</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Appointment" asp-action="Listappointment">Liste des RDV</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Broker" asp-action="CreateBroker">Ajouter un broker</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="AddCustomer">Ajouter un customer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Appointment" asp-action="AddAppointment">Ajouter un RDV</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Broker" asp-action="ListBrokers">Liste des brokers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="ListCustomers">Liste des customers</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - agenda - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>